### ISSUE TITLE
When i run an analysis through Cuckoo IOCaware_stix fails

### ISSUE THREAD

**Issue by s69mouse** [iocaware/iocgen#3]
Once the Cuckoo analysis finishes, i receive: 

2015-01-30 09:59:10,096 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "IOCAware_STIX":
Traceback (most recent call last):
  File "/home/rm/cuckoo/lib/cuckoo/core/plugins.py", line 499, in process
    current.run(self.results)
  File "/home/rm/Desktop/cuckoo/modules/reporting/ziocaware_stix.py", line 62, in run
    doCuckoo(results)
  File "/home/rm/Desktop/cuckoo/modules/reporting/ziocaware_stix.py", line 448, in doCuckoo
    metadata = {'malfilename':malfilename, 'malmd5':malmd5, 'malsha1':malsha1, 'malsha256':malsha256, 'malsha512':malsha512, \
UnboundLocalError: local variable 'malmd5' referenced before assignment
2015-01-30 09:59:10,097 [lib.cuckoo.core.scheduler] INFO: Task #3: reports generation completed (path=/home/rm/Desktop/cuckoo/storage/analyses/3)
2015-01-30 09:59:10,271 [lib.cuckoo.core.scheduler] INFO: Task #3: analysis procedure completed

I have not been able to figure out what is causing the error

**Comment by junkh3ap** [comment]
That's telling me that the MD5 was not calculated for some reason ("'malmd5' referenced before assignment). You could set the malmd5 to an empty string so that it's at least referenced, but if you're not getting an MD5, there's a bigger problem there in the first place.

Yeah, I know this is months late - sorry about that.
