### ISSUE TITLE
ERROR: Failed to run the reporting module "IOCAware_OpenIOC

### ISSUE THREAD

**Issue by shasta90** [iocaware/iocgen#5]
[lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "IOCAware_OpenIOC":
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 507, in process
    current.run(self.results)
  File "/opt/cuckoo/modules/reporting/iocaware_openioc.py", line 20, in run
    doCuckoo(results)
  File "/opt/cuckoo/modules/reporting/iocaware_openioc.py", line 258, in doCuckoo
    fileitems = results['target']['file']
KeyError: 'file'

Does the openioc.py script require modification or other?

**Comment by mjezorek** [comment]
It should not. It's possible that its out of date and needs to be updated with the new Cuckoo. Will look again at this
