### ISSUE TITLE
ERROR: Failed to run the reporting module "IOCAware_STIX"

### ISSUE THREAD

**Issue by shasta90** [iocaware/iocgen#6]
ERROR: Failed to run the reporting module "IOCAware_STIX":
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 507, in process
    current.run(self.results)
  File "/opt/cuckoo/modules/reporting/iocaware_stix.py", line 62, in run
    doCuckoo(results)
  File "/opt/cuckoo/modules/reporting/iocaware_stix.py", line 355, in doCuckoo
    staticitems = results['static']
KeyError: 'static'

Does the stix.py script require modification or other?

**Comment by mjezorek** [comment]
Probably the same problem as the OpenIOC one. I will look at this soon as I need this for some work as well
